[workspace]

members = [
  "crates/core",
  "crates/napi",
  "crates/wasm",
  "crates/next-binding",
  "crates/next-build",
  "crates/next-core",
  "crates/next-dev",
  "crates/next-dev-tests",
  "crates/next-transform-font",
  "crates/next-transform-dynamic",
  "crates/next-transform-strip-page-exports",
]

[profile.dev.package.swc_css_prefixer]
opt-level = 2

# This is a workaround for wasm timeout issue
[profile.dev.package."*"]
debug-assertions = false

[profile.release]
lto = true

[workspace.dependencies]
# Workspace crates
next-binding = { path = "crates/next-binding" }
next-core = { path = "crates/next-core", default-features = false }
next-dev = { path = "crates/next-dev" }
next-dev-tests = { path = "crates/next-dev-tests" }
next-transform-font = { path = "crates/next-transform-font" }
next-transform-dynamic = { path = "crates/next-transform-dynamic" }
next-transform-strip-page-exports = { path = "crates/next-transform-strip-page-exports" }

# SWC crates
# Keep consistent with preset_env_base through swc_core
browserslist-rs = { version = "0.12.2" }
mdxjs = { version = "0.1.9" }
modularize_imports = { version = "0.26.14" }
styled_components = { version = "0.53.14" }
styled_jsx = { version = "0.30.14" }
swc_core = { version = "0.72.0" }
swc_emotion = { version = "0.29.14" }
testing = { version = "0.32.0" }

# Turbo crates
auto-hash-map = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
node-file-trace = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-malloc = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update", default-features = false }
turbo-tasks = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-build = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-bytes = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-env = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-fetch = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update", default-features = false }
turbo-tasks-fs = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-hash = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-macros = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-macros-shared = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-memory = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbo-tasks-testing = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-cli-utils = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-core = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-create-test-app = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-css = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-dev = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-dev-server = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-ecmascript = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-env = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-json = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-mdx = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-node = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-static = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-swc-utils = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }
turbopack-test-utils = { git = "https://github.com/vercel/turbo.git", branch = "kdy1/swc-update" }

# General Deps

# Be careful when selecting tls backend, including change default tls backend.
# If you changed, must verify with ALL build targets with next-swc to ensure
# it works. next-swc have various platforms, some doesn't support native (using openssl-sys)
# and some aren't buildable with rustls.
reqwest = { version = "0.11.14", default-features = false }

chromiumoxide = { version = "0.4.0", features = [
  "tokio-runtime",
], default-features = false }
# For matching on errors from chromiumoxide. Keep in
# sync with chromiumoxide's tungstenite requirement.
tungstenite = "0.17.3"

# flate2_zlib requires zlib, use flate2_rust
allsorts = { version = "0.14.0", default_features = false, features = ["outline", "flate2_rust"] }
anyhow = "1.0.69"
assert_cmd = "2.0.8"
async-compression = { version = "0.3.13", default-features = false, features = [
  "gzip",
  "tokio",
] }
async-trait = "0.1.64"
atty = "0.2.14"
chrono = "0.4.23"
clap = "4.1.6"
clap_complete = "4.1.2"
concurrent-queue = "2.1.0"
console = "0.15.5"
console-subscriber = "0.1.8"
criterion = "0.4.0"
dashmap = "5.4.0"
dialoguer = "0.10.3"
dunce = "1.0.3"
futures = "0.3.26"
futures-retry = "0.6.0"
httpmock = { version = "0.6.7", default-features = false }
indexmap = "1.9.2"
indicatif = "0.17.3"
indoc = "2.0.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
mime = "0.3.16"
nohash-hasher = "0.2.0"
once_cell = "1.17.1"
owo-colors = "3.5.0"
parking_lot = "0.12.1"
pathdiff = "0.2.1"
pin-project-lite = "0.2.9"
predicates = "2.1.5"
pretty_assertions = "1.3.0"
proc-macro2 = "1.0.51"
qstring = "0.7.2"
quote = "1.0.23"
rand = "0.8.5"
regex = "1.7.0"
rstest = "0.16.0"
rustc-hash = "1.1.0"
semver = "1.0.16"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
serde_qs = "0.11.0"
serde_yaml = "0.9.17"
syn = "1.0.107"
tempfile = "3.3.0"
thiserror = "1.0.38"
tiny-gradient = "0.1.0"
tokio = "1.25.0"
tokio-util = { version = "0.7.7", features = ["io"] }
tracing = "0.1.37"
url = "2.2.2"
urlencoding = "2.1.2"
webbrowser = "0.8.7"
